language: python

python:
  - 3.6

services: postgresql

install:
  - pip install -r requirements.txt
  - pip install coverage python-coveralls flake8

before_script:
  - cp local_settings.template.py local_settings.py
  - psql -c "CREATE DATABASE testdb;" -U postgres

script:
  - coverage run --source=. ./manage.py test
  - flake8 .

after_success:
  - coveralls
